CREATE TABLE Is_Supplied_By (
    BookID INT,
    SupplierID INT,
    PRIMARY KEY (BookID, SupplierID),
    FOREIGN KEY (BookID) REFERENCES Book(BookID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (SupplierID) REFERENCES Supplier(SupplierID)
        ON DELETE CASCADE ON UPDATE CASCADE
);
