CREATE TABLE Managed_By (
    EmployeeID INT PRIMARY KEY,
    ManagerID INT,
    FOREIGN KEY (EmployeeID) REFERENCES Employee(EmployeeID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ManagerID) REFERENCES Manager(ManagerID)
        ON DELETE CASCADE ON UPDATE CASCADE
);
