CREATE TABLE Serves_As (
    CashierID INT PRIMARY KEY,
    EmployeeID INT UNIQUE,
    FOREIGN KEY (CashierID) REFERENCES Cashier(CashierID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (EmployeeID) REFERENCES Employee(EmployeeID)
        ON DELETE CASCADE ON UPDATE CASCADE
);
